### ISSUE TITLE
Issue: STL Fussion not able to deal with recursive loops in classes to serialize

### ISSUE THREAD

**Issue by devedse** [servicetitan/Stl.Fusion#187]
I've been trying to build an app based on Stl.Fusion but I'm running into some issues with serialisation of data objects from Server to Client.

The reason being that my DbClasses contain a recursive loop. E.g.:

```
    public record DbShop : LongKeyedEntity
    {
        [Required, MaxLength(120)]
        public string Name { get; set; } = "";

        public ICollection<DbShopItem> ShopItems { get; set; } = new List<DbShopItem>();



        [MaxLength(9999)]
        public string XPathPrice { get; set; } = "";
        [MaxLength(9999)]
        public string XPathAvailability { get; set; } = "";
        [MaxLength(9999)]
        public string AvailabilityText { get; set; } = "";
    }

    public record DbShopItem : LongKeyedEntity
    {
        [Required, MaxLength(120)]
        public string Name { get; init; } = "";

        [Required, MaxLength(9999)]
        public string Url { get; init; } = "";

        [MaxLength(9999)]
        public string LastPrice { get; init; } = "";
        public bool LastAvailable { get; init; } = false;
        [MaxLength(9999)]
        public string LastAvailableText { get; init; } = "";


        [Required, ForeignKey("DbStonkyShop")]
        public long DbStonkyShopId { get; init; }

        //[Required]
        //public DbStonkyShop? DbStonkyShop { get; init; }
    }
```

Normally you can configure ASP.NET Core controllers to ignore this by adding the following code:

```
services.AddMvc().AddNewtonsoftJson(options =>
{
    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
})
```

However when I do this I run into some issues where STL Fusion makes use of their own JSON serializers which ignore this configuration.

For example the `JsonNetSerializer` class has its own `DefaultSettings`. Which can't be changed.

It seems though that in other places the normal `JsonConvert.Serialize(...)` method is used. With this you can actually override defaults by using `JsonConvert.DefaultSettings`.

**Comment by alexyakunin** [comment]
> where STL Fusion makes use of their own JSON serializers which ignore this configuration.

Hi @devedse , it uses JSON.NET as well, and I think this specific option should be easy to change. Here is how you can find every place where Fusion configures something related to JSON:

![image](https://user-images.githubusercontent.com/1673423/100091287-41e45b00-2e09-11eb-8386-2b97c0cf947a.png)

As for why your attempt to change this didn't work, it's because there are at least 4 places where serialization & deserialization happens:
- Server-side: ASP.NET Core + server-side WebSocket channel
- Client-side: RestEase deserialization + client-side WebSocket channel

The screenshot shows some of these places; the WebSocket-related serializers are configured here:
![image](https://user-images.githubusercontent.com/1673423/100091868-12821e00-2e0a-11eb-8f14-40868a4f75f2.png)
![image](https://user-images.githubusercontent.com/1673423/100092004-42c9bc80-2e0a-11eb-8618-267df15afe7f.png)

In both these cases `ChannelSerializerPairFactory` can be provided via `WebSocketChannelProvider.Options` or `WebSocketServer.Options`.

**Comment by alexyakunin** [comment]
Besides that:

1. https://github.com/servicetitan/Stl.Fusion/commit/1919aa8ea67fb9437c82fdd9c2844528fbbf2c3b - all your problems are gone now, + you can change the defaults as you like (just remember to do this before calling any Fusion stuff).

2. Consider using `[JsonIgnore]` or a different type to send to the client. Typically, people map DB record/entity type to something else (model type) before they send it.

**Comment by alexyakunin** [comment]
Please LMK if it's ok to close this issue :)

**Comment by devedse** [comment]
@alexyakunin , wow you're amazing! 😄

Hopefully I'll have some time later today or tomorrow to test everything out.

Are you open for some more feedback for Stl.Fusion? (Shall I make a new issue for that)

**Comment by alexyakunin** [comment]
Absolutely 👍 As for the issues, if you're fine with Discord, a faster way to resolve question-style topics is to ask q. there first, but this is totally optional. Creating issues is actually better in the long run, since they can be googled :)
