### ISSUE TITLE
Commands are executed twice?

### ISSUE THREAD

**Issue by ichthus1604** [servicetitan/Stl.Fusion#557]
Running the `HelloCart` sample from https://github.com/servicetitan/Stl.Fusion.Samples it can be observed that `InMemoryProductService.Edit()` is executed TWICE each time the client modifies a product (after initialization)

Steps to reproduce:

 - Clone https://github.com/servicetitan/Stl.Fusion.Samples
 - Run `HelloCart` example
 - Select option `#1 `
 - After `Initialize()` has run, but before entering a new `product=price` in the console, place a breakpoint in `InMemoryProductService` line 9
 - Enter a `product=price` value in the console and hit Enter
 - Observe breakpoint being hit twice.

**Comment by alexyakunin** [comment]
Hi, this is expected behavior: every command runs once in "normal" mode first, and once it completes, it runs in invalidation mode, which happens once on _every_ host.

You may notice there is `if (Computed.IsInvalidating()) ...` in the body of this method - that's where the second run is detected & processed differently.

See the last parts of the tutorial covering how invalidation works in cluster.

**Comment by ichthus1604** [comment]
@alexyakunin Thanks for the quick response!

BTW, I've followed the docs and the samples and managed to get a working client/server toy project.
IMO it would be easier if `HelloCart` was separated in this way, such that it makes it easier to understand what parts belong where.

Other than that, a big THANK YOU for the effort and the quality you've put into this project.

**Comment by alexyakunin** [comment]
Got it. K, I guess I'm closing this issue :)
